language: php
sudo: false

cache:
  directories:
    - $COMPOSER_CACHE_DIR

php:
  - 7.1
  - 7.2

stages:
  - name: Test coverage
    if: (NOT type IN (pull_request)) AND (branch = master)
  - name: API docs build
    if: (NOT type IN (pull_request)) AND (branch = master)
  - name: HTML docs deploy
    if: (NOT type IN (pull_request)) AND (branch = master)

before_install:
  - composer self-update
  - if [[ $TEST_COVERAGE != true ]]; then phpenv config-rm xdebug.ini || return 0 ; fi

install:
  - travis_retry composer install -n --prefer-source
  - if [[ $TEST_COVERAGE == true ]]; then travis_retry composer test-coverage-install || return 0 ; fi

script: composer test

jobs:
  allow_failures:
    - php: 7.2
  include:
    - stage: Test coverage
      php: 7.1
      env:
        - TEST=true
        - TEST_COVERAGE=true
      before_script:
        - mkdir -p build/logs
      script:
        - travis_retry composer test-coverage
      after_success:
        - travis_retry composer test-coverage-upload
    - stage: API docs build
      install: travis_retry composer require sami/sami
      script: composer api-docs-build
    - stage: HTML docs deploy
      install: skip
      script: skip
      deploy:
        provider: script
        script: bash scripts/deploy-docs.sh
        skip_cleanup: true
        overwrite: true
        on:
          branch: master
          php: '7.1'
