language: php

php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm

install:
    - composer self-update

before_script:
    - composer install --no-interaction
    - mkdir -p build/logs

script:
    #- phpunit --coverage-clover=coverage.clover
    - phpunit -c ./ --coverage-text --coverage-clover build/logs/clover.xml

after_script:
    #- wget https://scrutinizer-ci.com/ocular.phar
    #- php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    - php vendor/bin/coveralls -v
