language: php
# faster builds on new travis setup not using sudo
sudo: false
# PHP versions
php:
  - 7.1
  - 7.2
matrix:
  include:
    - php: 5.6
      env: COVERAGE=run API_DOCS=build
  allow_failures:
    - php: 7.2
  fast_finish: true
# cache vendor dirs
cache:
  directories:
    - vendor
    - $COMPOSER_CACHE_DIR
# update composer it-self
install:
  - composer self-update
# install package
before_script:
  #- phpenv config-rm xdebug.ini
  - composer install --no-interaction
  - if [[ $COVERAGE = run ]]; then mkdir -p build/logs; PHPUNIT_FLAGS="--coverage-text --coverage-clover build/logs/clover.xml"; fi
# run PHPUnit and export code coverage log
script:
  - if [[ $COVERAGE = run ]]; then phpunit -c ./ $PHPUNIT_FLAGS; fi
# docs & co
after_success:
  # run coveralls
  - if [[ $COVERAGE = run ]]; then travis_retry php bin/coveralls -v; fi
  # build API docs
  - if [[ $API_DOCS = build ]]; then vendor/bin/sami.php update sami.php; fi
  # deploy docs
  - bash deploy-docs.sh
