language: php
sudo: false

matrix:
  include:
    - php: 5.6
      env:
        - LEGACY_DEPS="phpunit/phpunit"
    - php: 7.1
      env:
        - LEGACY_DEPS="phpunit/phpunit"
        - TEST_COVERAGE=true
    - php: 7.2
  allow_failures:
    - php: 7.2
  fast_finish : true

stages:
  - test
  - test-coverage
  - api-docs-build
  - html-docs-deploy

before_install:
  - composer self-update
  - if [[ $TEST_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi

install:
  - travis_retry composer install --no-interaction
  - if [[ $LEGACY_DEPS != '' ]]; then travis_retry composer update --no-interaction --with-dependencies $LEGACY_DEPS ; fi

script: composer test

jobs:
  include:
    - stage: test
    - stage: test-coverage
      php: 7.1
      env: TEST_COVERAGE=true
      install:
        - composer test-coverage-install
      before_script:
        - mkdir -p build/logs
      script:
        - composer test-coverage
      after_success:
        - composer test-coverage-upload
    - stage: api-docs-build
      php: 7.1
      script: composer api-docs-build
    - stage: html-docs-deploy
      php: 7.1
      script: bash deploy-docs.sh

cache:
  directories:
    - $COMPOSER_CACHE_DIR
