language: php
# faster builds on new travis setup not using sudo
sudo: false
# PHP versions
php:
  - 5.6
  - 7.1
  - 7.2
matrix:
  allow_failures:
    - php: 7.2
  fast_finish: true
# cache vendor dirs
cache:
  directories:
    - vendor
    - $COMPOSER_CACHE_DIR
# update composer it-self
install:
  - composer self-update
# install package
before_script:
  #- phpenv config-rm xdebug.ini
  - composer install --no-interaction
  - mkdir -p build/logs
# run PHPUnit and export code coverage log
script:
  #- phpunit -c ./ --coverage-text --coverage-clover build/logs/clover.xml
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then phpunit -c ./ --coverage-text --coverage-clover build/logs/clover.xml; fi
# docs & co
after_success:
  # run coveralls
  #- travis_retry php vendor/bin/coveralls -v
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then travis_retry php vendor/bin/coveralls; fi
  # build API docs
  #- vendor/bin/sami.php update sami.php
  # deploy docs
  - bash deploy-docs.sh
