language: php
sudo: false # faster builds on new travis setup not using sudo
# PHP versions
php:
  - 7.1
  - 7.2
matrix:
  include:
    - php: 5.6
      env: COVERAGE=run API_DOCS=build
  allow_failures:
    - php: 7.2
  fast_finish: true
# cache Composer files
cache:
  directories:
    - vendor
    - $COMPOSER_CACHE_DIR
install:
  # update composer it-self
  - composer self-update
  # install coveralls.phar
  - wget -c -nc --retry-connrefused --tries=0 https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar -O coveralls.phar
  - chmod +x coveralls.phar
  - php coveralls.phar --version
before_script:
  #- phpenv config-rm xdebug.ini
  # install packages
  - composer install --no-interaction
  - if [[ $COVERAGE = run ]]; then mkdir -p build/logs; PHPUNIT_FLAGS="--coverage-text --coverage-clover build/logs/clover.xml"; fi
script:
  # run PHPUnit and export code coverage log
  - if [[ $COVERAGE = run ]]; then phpunit -c ./ $PHPUNIT_FLAGS; fi
# docs & co
after_success:
  # submit coverage report to Coveralls
  - if [[ $COVERAGE = run ]]; then travis_retry php coveralls.phar -v; fi
  # Submit coverage report to codecov.io
  - bash <(curl -s https://codecov.io/bash)
  # build API docs
  - if [[ $API_DOCS = build ]]; then vendor/bin/sami.php update sami.php; fi
  # deploy docs
  - bash deploy-docs.sh
