language: php
sudo: false

cache:
  directories:
    - $COMPOSER_CACHE_DIR

php:
  - 5.6
  - 7.1
  - 7.2

stages:
  - test-coverage
  - api-docs-build
  - html-docs-deploy

before_install:
  - composer self-update
  - if [[ $TEST_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi

install:
  - travis_retry composer install -n --prefer-source
  - if [[ $TEST_COVERAGE != 'true' ]]; then travis_retry composer test-coverage-install || return 0 ; fi

script: composer test

jobs:
  allow_failures:
    - php: 7.2
  include:
    - stage: test-coverage
      php: 5.6
      env: TEST_COVERAGE=true
      before_script:
        - mkdir -p build/logs
      script:
        - travis_retry composer test-coverage
      after_success:
        - travis_retry composer test-coverage-upload
    - stage: api-docs-build
      php: 7.1
      script: composer api-docs-build
    - stage: html-docs-deploy
      php: 7.1
      script: bash deploy-docs.sh
