language: php
php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - nightly

matrix:
allow_failures:
    - 7.0

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --dev --no-interaction --prefer-source

script:
    - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

sudo: false

cache:
    directories:
        - $HOME/.composer/cache