language: php
sudo: false
php:
  - 5.6
  - 7.1
  - 7.2

stages:
  - test
  - test-coverage
  - api-docs-build
  - html-docs-deploy

before_install:
  - composer self-update
  - if [[ $TEST_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi

install:
  - travis_retry composer install --no-interaction

script: composer test

jobs:
  include:
    - stage: test-coverage
      php: 5.6
      env: TEST_COVERAGE=true
      install:
        - travis_retry composer update --no-interaction
        - composer test-coverage-install
      before_script:
        - mkdir -p build/logs
      script:
        - composer test-coverage
      after_success:
        - composer test-coverage-upload
    - stage: api-docs-build
      php: 7.1
      script: composer api-docs-build
    - stage: html-docs-deploy
      php: 7.1
      script: bash deploy-docs.sh

cache:
  directories:
    - $COMPOSER_CACHE_DIR
