language: php
# PHP versions
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
# faster builds on new travis setup not using sudo
sudo: false
# cache vendor dirs
cache:
  directories:
    - vendor
    - $COMPOSER_CACHE_DIR
# update composer it-self
install:
  - composer self-update
# install package
before_script:
  - composer install --no-interaction
  - mkdir -p build/logs
# run PHPUnit and export code coverage log
script:
  - phpunit -c ./ --coverage-text --coverage-clover build/logs/clover.xml
# run coveralls
after_script:
  - php vendor/bin/coveralls -v
# deploy docs
deploy:
  provider: script
  script: ./deploy.sh
  skip_cleanup: true
  overwrite: true
  on:
    branch: master
    php: '5.6'
