version: 2
jobs:
    test:
      docker:
        - image: circleci/php:7.1
      timezone:
        Europe/Paris
      steps:
        - checkout
        - run:
            name: Composer
            comand: |
              sudo composer self-update
              composer install --no-interaction
        - run: 
            name: PHPUnit
            command: |
              mkdir -p ~/phpunit
              phpunit --log-junit ~/phpunit/junit.xml
            when: always
        - store_test_results:
            path: ~/phpunit
        - store_artifacts:
            path: ~/phpunit
